### ISSUE TITLE
pkgdown get started and index

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#102]
How is the index.html generated? Could it just be the same as "get started" or redirect index to "get started"? I think they are redundant (index/home is kind of a get started page).

**Comment by shevandrin** [comment]
> The main content of the home page (index.html) is generated from pkgdown/index.md, index.md, or README.md, in that order.
https://pkgdown.r-lib.org/reference/build_home.html

we can delete 'get started' to avoid redundant

**Comment by johannes-titz** [comment]
It might not be clear where the home page is located, though. I have to click on qti on the left-hand side. I think redundancy in this case would be ok, unless it is inconvenient to handle.
