### ISSUE TITLE
section() has to work with task object, AssessmentSection and files

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/qti#103]
in helper `section()`:

- [x] param file -> ???
- [x] implement mechanic to work with task objects
- [x] implement mechanic to work with AssessmentSection objects
- [x] implement mechanic to work with AssessmentItem objects

**Comment by shevandrin** [comment]
what do you think if i change 'file' to 'content' in `section() `? @johannes-titz

**Comment by johannes-titz** [comment]
I like it.

**Comment by shevandrin** [comment]
@bondarenko-petr please cover new features with tests
