### ISSUE TITLE
new test: Check how overall points are delivered

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/qti#118]
Check value of 'points' slot AssessmentTest object in case of different hierarchy of value of 'section' slot (different combination of sections and tasks, different hierarchy depth)

**Comment by bondarenko-petr** [comment]
I checked the following case:

![2023-12-15_15-11-44](https://github.com/shevandrin/qti/assets/117097478/d4a61af4-77bb-48b9-9452-35e390d9ad57)

All is ok
