### ISSUE TITLE
rstudio project template improvements

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#122]
- [x] Consider naming it simply "QTI Project."
- [x] Introduce the option to set `QTI_API_ENDPOINT`, defaulting to bps.
- [x] Introduce the option `QTI_AUTOSTART_SERVER`, defaulting to TRUE.
- [x] Explore the feasibility of allowing users to choose between the qtijs and opal renderers, with corresponding adjustments to the templates. This requires discussion, and implementation complexity should be taken into account.
- [x] Default to qtijs renderer as Opal might be less common.
- [x] Explore the addition of an R script to generate a well-structured default exam for the project.
- [x] change to: Create templates Yes/No
- [x] include in starting script: creation two sections (permanent and with randomization), create test with params (time, attempts), create test for opal (files, calculator), render_zip()
- [x] organize Rmd template in separate folders
- [x] change the start page in terms of working with the project template
- [ ] #136

Regarding main.R:

- [x] " exercises_r" is too unspecific, how about exercises_random? 
- [x] permanent_section -> section_fixed
- [x] variable_section -> section_random
- [x] 4 variants
- [x] could we use a proper pdf file for upload? e.g. formelsammlung: https://github.com/johannes-titz/formelsammlung/blob/main/main.pdf -> maybe the best way would be to download it from R or have a helper function to do that.
- [x] I think 1 attempt makes more sense
- [x] test_folder -> upload
- [x] test_opal@academic_grading = TRUE, test_opal@grade_label = "Note" -> these should be parameters for test and test4opal I guess?
- [x] muster_test_opal -> test_demo
- [x] assignment operators for exercises and exercises_random are incorrect, use -> instead of =

**Comment by shevandrin** [comment]
> * test_opal@academic_grading = TRUE, test_opal@grade_label = "Note" -> these should be parameters for test and test4opal I guess?

i am going to create these as parameters of test() and test4opal() functions, what do you think about default values for them?

**Comment by johannes-titz** [comment]
I think it should actually be turned off by default because many exams cannot be graded automatically and it might lead to confusion.
