### ISSUE TITLE
Title of exercise when knitted via render_opal

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#124]
Example: https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/42901766145;jsessionid=DAFCF6C02EE829B95ED4A877DB876BA1.opalN6?0

At the top it is: knit_test_singlechoice, can we provide a better name?

**Comment by shevandrin** [comment]
@johannes-titz of course we can) my idea was to add prefix "knit" not to make a mess in a personal repo on Opal. If i got something in my personal repo with the name starting with 'knit'  i know the reason and  source of this file.
We can take other prefix, any ideas?

**Comment by johannes-titz** [comment]
Okay, knit makes sense from this perspective. Maybe without test then? It is always a test I guess.
