### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#13]
Error in .install_package_code_files(".", instdir) : 
files in '/tmp/Rtmp8CNTGJ/R.INSTALL1a938e15119282/qti/R' missing from 'Collate' f
ield:
  knit_functions.R

Does it work for you? If no, please check that build and install work before pushing a commit. I would like to test the rmd rendering. (It is not urgent, though.)

It would also be good to set up github actions for automatic building (see r-pkgs book).

**Comment by shevandrin** [comment]
use_github_actions()
