### ISSUE TITLE
code chunks line breaks not displayed when in markdown subsection

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#131]
https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/43005902848?6

To reproduce use a subsection (##) and then an r code chunk:

```{r}
stem(rnorm(20, 100, 10))
```

You can also see the code on OPAL.

**Comment by shevandrin** [comment]
Hallo Johannes,

es wäre gut, wenn du mir die ganze Rmd Datei schicken würdest, um diesen
Fall zu recherchieren.
Vielen Dank im Voraus.
bis gleich.
Best greetings
Andrey Shevandrin


вт, 16 янв. 2024 г. в 08:52, Johannes Titz ***@***.***>:

**Comment by shevandrin** [comment]
if it works now, i kindly ask you to close the issue ;)
