### ISSUE TITLE
strange error after update

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#132]
Error in yaml.load(readLines(con, warn = readLines.warn), error.label = error.label,  : 
  (/home/jt/R/x86_64-pc-linux-gnu-library/4.3/qti/rmarkdown/templates/multiplechoice-complex/template.yaml) Scanner error: mapping values are not allowed in this context at line 1, column 10

Does not look severe, bu wanted to report it nevertheless. It happens when I try to open an Rmarkdown Template.

**Comment by shevandrin** [comment]
if it works now, i kindly ask you to close the issue ;)
