### ISSUE TITLE
error when using long colnames/rownames in table

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#134]
<pre>

---
type: sc
knit: qti::render_opal
---

# question

```{r echo=F}
tab <- round(matrix(rnorm(9), ncol = 3), 2)
tab
colnames(tab) <- c(c("a", "b", "very very very very long string"))
rownames(tab) <- c(c("a", "very very very long string", "c"))
knitr::kable(tab)
```

An alpha error of 5% means that:

- There is a 5% probability that you will mistakenly reject the null hypothesis, when it is actually correct. 
- There is a 5% probability that the null hypothesis is correct.
- There is a 5% probability that you will mistakenly reject the alternative hypothesis, when it is correct.
- The test power is 95%.
</pre>

This gives: 

Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
  Opening and ending tag mismatch: col line 26 and colgroup [76]
Calls: <Anonymous> ... create_qti_task -> <Anonymous> -> read_xml.character -> read_xml.raw
Execution halted

I am not sure when it happens, but usually with long row/colnames.

**Comment by shevandrin** [comment]
this Rmd now works good:
https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/43081531394?6

if the outcome meets your requirements, please close the issue
