### ISSUE TITLE
error, if xml contains html entities

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/qti#144]
```
librarian::shelf(qti, mathml)
task <- new("Essay")
task@content <- list("<math><mrow><mover accent=\"true\"><mi>p</mi><mo>&Hat;</mo></mover><mo>&pm;</mo><mrow><mi>z</mi><mo>&sdot;</mo><msqrt><mstyle displaystyle=\"true\"><mfrac><mrow><mover accent=\"true\"><mi>p</mi><mo>&Hat;</mo></mover><mo>&sdot;</mo><mrow><mo>(</mo><mrow><mn>1</mn><mo>-</mo><mover accent=\"true\"><mi>p</mi><mo>&Hat;</mo></mover></mrow><mo>)</mo></mrow></mrow><mi>N</mi></mfrac></mstyle></msqrt></mrow></mrow></math>")
upload2opal(task, display_name="issue_144")
```

outcome:
 https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/43123802114?0

https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/43123802115?0
@johannes-titz i would ask you to try it with your examples

**Comment by shevandrin** [comment]
if it meets your requirements, than we need to change the xml in tests

**Comment by johannes-titz** [comment]
I will test it out, but I will need some time. I just created the exam for this semester and do not want to introduce any changes until the exam is fixed.

**Comment by shevandrin** [comment]
@johannes-titz i change the approach, now i used html decoder and deleted DOCTYPE

**Comment by johannes-titz** [comment]
Did you experience performance issues with the prior implementation too?

Okay, maybe you can show me how it is implemented, I am interested.

**Comment by johannes-titz** [comment]
This works; I did not experience any problems with loading so far. I will close it for now.
