### ISSUE TITLE
Collect individual answers from exam result

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/qti#18]
input: xml file with exam results
output as dataframe with fields:
- question_identifier
- correct_response
- candidate_response

**Comment by shevandrin** [comment]
get_result_attr_answers() and get_result_attr_options()
a9fb95d8e06d8967ef41ccd6cf0f32e0151d840a

**Comment by shevandrin** [comment]
> By the way, maybe there are better names for these functions? Maybe just `extract_questions` and `extract_responses`? Or is this too unspecific?

I like them, shorter is better. To make them more specific we can add  'exam' like: extract__exam_questions() and extract_exam_responses(), but it is only one symbol less than 'get_result_attr_answers' 😂

**Comment by johannes-titz** [comment]
Are we not always extracting from an exam? If so, I think we can leave it out. But maybe I am missing something. Naming stuff is always the hardest part! :)

**Comment by shevandrin** [comment]
I added new column "is_answer_given"

**Comment by johannes-titz** [comment]
Just updated from github, but cannot see a column "is_answer_given".

**Comment by johannes-titz** [comment]
Yep, just with a typo :), but that was not the problem, actually. R was not re-loading the library.

**Comment by johannes-titz** [comment]
Before we close this, can we also have the title from ONYX displaying? I believe these are currently the file names because I set it up in exams this way. Would be quite useful to compare all the data we already collected. But maybe it is not possible, just let me know.

**Comment by shevandrin** [comment]
> Before we close this, can we also have the title from ONYX displaying? I believe these are currently the file names because I set it up in exams this way. Would be quite useful to compare all the data we already collected. But maybe it is not possible, just let me know.

unfortunately, I dont get your idea about titles form ONYX. Could you post here a screenshot form ONYX with titles?

**Comment by johannes-titz** [comment]
![onyx](https://user-images.githubusercontent.com/32065313/227179949-68567906-d963-469d-995f-6e3a63df254d.png)

I guess it is not possible, I think you told me this already. Maybe it would be possible when having the exam? Could we make it optional then? For instance, if I download from OPAL, I will always get the exam xml files (questions).

**Comment by shevandrin** [comment]
if you mean titles in 'Aufgabe' column, then it is not possible, because in xml there is no tag or attr with title of task, only identifiers

**Comment by johannes-titz** [comment]
Ok I see. What if we have the exam files?

**Comment by shevandrin** [comment]
in this case we can get titles via identifiers

**Comment by shevandrin** [comment]
@johannes-titz , i added new function extract_result_zip() to work with opal zip archive, it works with answers and options, parameter 'details' controls this
@bondarenko-petr could you make more meaningful identifiers in your mock test, just use the naming scheme that we have already discussed

**Comment by johannes-titz** [comment]
Sounds great, I will test it. The zip from OPAL is a bit problematic because all files have the same name. How did you handle this? When I worked with the functions last week, I extracted them from the zip archive with a flag that set the name to the parent directory.

**Comment by shevandrin** [comment]
> Sounds great, I will test it. The zip from OPAL is a bit problematic because all files have the same name. How did you handle this? When I worked with the functions last week, I extracted them from the zip archive with a flag that set the name to the parent directory.

i used temp dir and worked with extracted files one by one via cycle

**Comment by johannes-titz** [comment]
what is the name of file_name after reading it in? Does every file have a different file name? This should be the case, but with OPAL it is a bit complicated. Anyway, I will test it and we can talk about it on Friday.

**Comment by shevandrin** [comment]
> what is the name of file_name after reading it in? Does every file have a different file name? This should be the case, but with OPAL it is a bit complicated. Anyway, I will test it and we can talk about it on Friday.

i just got you point, i will fix it ;)

**Comment by shevandrin** [comment]
> what is the name of file_name after reading it in? Does every file have a different file name? This should be the case, but with OPAL it is a bit complicated. Anyway, I will test it and we can talk about it on Friday.

#c155447

now it takes the name of zip file with individual answers

**Comment by shevandrin** [comment]
> if you mean titles in 'Aufgabe' column, then it is not possible, because in xml there is no tag or attr with title of task, only identifiers

@johannes-titz  i add new column 'titles' to the data frame of extract_result_zip(), it takes titles from the test file, but identifiers must be unique within the test, i am not sure that this condition is always true

**Comment by johannes-titz** [comment]
Sounds good, I will try it out and give feedback.

**Comment by johannes-titz** [comment]
Hi Andrey,

I just tried it, but get the following error:

```
qti::extract_result_zip(file)
Error in utils::unzip(file.path(test_dir, test_file), list = TRUE) : 
  invalid zip name argument
```

but `utils::unzip(file)` works. Does it work with relative paths? I have the zip under `archive/file.zip`

**Comment by johannes-titz** [comment]
Ah, maybe I misunderstood. There are two levels of zip files. You probably work on the upper one. Let me try.

**Comment by johannes-titz** [comment]
Ok, still does not work. I guess the test-zip file has a certain name? Maybe pass it as a parameter, or search for zip files? In my case the test is called qtitest.zip :). How about a default parameter, but when it is not in the folder, through an error that the parameter is required?

**Comment by johannes-titz** [comment]
> > if you mean titles in 'Aufgabe' column, then it is not possible, because in xml there is no tag or attr with title of task, only identifiers
> 
> @johannes-titz i add new column 'titles' to the data frame of extract_result_zip(), it takes titles from the test file, but identifiers must be unique within the test, i am not sure that this condition is always true

I think this is fine because different exams have different dates, so we should always be able to separate same titles from different exams. It's also just for the old data. With the new data we can work with the identifiers.

**Comment by shevandrin** [comment]
> Ok, still does not work. I guess the test-zip file has a certain name? Maybe pass it as a parameter, or search for zip files? In my case the test is called qtitest.zip :). How about a default parameter, but when it is not in the folder, through an error that the parameter is required?

I have to look at your zip file 🤔

**Comment by johannes-titz** [comment]
Not so easy because data is not anonymous. Does it work with Petr's example? What if you rename the zip file? It it works with his, I will provide you with my zip file. Maybe another test case.

**Comment by shevandrin** [comment]
The function works with peters mock test results. At least I need to know the names of files that your zip contains. I used suffix "result.zip" to detect what kind of current xml is. Probably in your archive the naming is different

**Comment by johannes-titz** [comment]
Yep, the name is qtitest.zip; I mean of the actual exam, not the participant result files. I think it is easier to provide an argument so the user can set the name in case it is different. For instance, getting some results from a colleague who uses OPAL but not our package.
