### ISSUE TITLE
create_qti_task requires "results" folder in working dir

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#21]
If there is no results folder, it will fail. Can we create this folder? or can we specify a path in the function? Not sure what would be best.

**Comment by shevandrin** [comment]
I see 'results' folder in repo. But you can create it

**Comment by johannes-titz** [comment]
if you use the package as a user, you will not have the results folder

**Comment by shevandrin** [comment]
solved here:
https://github.com/shevandrin/qti/commit/6e653487a9f8fa19d5625cb07b5fea0abc86b244
