### ISSUE TITLE
Is it possible to have functions to create S4 objects instead of the command new?

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#25]
The problem is that there is no autocompletion for `new`. So if I do something like:

```
new("SingleChoice", ...)
```

RStudio and other IDEs do not suggest parameters. I believe in S3 it is common to define a function that creates the object, which solves the problem. How is it in S4? Can we have a function SingleChoice that creates the SingleChoice object? Are there any best practices?

**Comment by shevandrin** [comment]
try functon singleChoice()
3671df669366aa764d268f48082e45cd618573ce
can it be a good solutions?

**Comment by johannes-titz** [comment]
Yes, this works, but I would like to see the implementation first. Also, title is now a required parameter, but was not before. How are other S4 packages handling this?

**Comment by shevandrin** [comment]
try to use Essay() as a constructor of Essay-class. As far I undersntand this this a conventional way to build constructor for S4 classes. And I also assign to title value of identifier if  user havent specified title. Opal uses titles to make links on tasks.

**Comment by johannes-titz** [comment]
Works for me, but Essay is not an exported function. I also thought this is the conventional way to call the constructor.

**Comment by johannes-titz** [comment]
@bondarenko-petr when you finish implementing this for all classes, you can close the issue.

**Comment by shevandrin** [comment]
i fixed the  problem with init. Now SingleChoice() works.
5574871c8ff0e722ee08994dea2981741c06ed3d
@bondarenko-petr can you do the same constractor functions for TextGap NumGap and TextGapOpal. And you can cover this functions with tests ;)
