### ISSUE TITLE
example for AssessmentTest does not work

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#26]
```
simple_test <- new("AssessmentTest", section = list(new("AssessmentSection", title = "sec1",
                                                        assessment_item = list(new("AssessmentItemRef", identifier = "id1", href = "convictive_agama.xml")))),
                   title = "simpliest test",
                   points = 1)
create_qti_test(simple_test)
qti(simple_test)
```

gives: could not find function create_qti_test
same for qti

Are they exported?

I am also wondering if `simple_test <- new...` should not fail because I do not have the convictive_agama.xml on my path.

**Comment by shevandrin** [comment]
this function is not exported, today I ve started refactoring test creating part. I want to make it possible to create test using AssessmentItem objects insted of their xml files
