### ISSUE TITLE
How to use sections with items?

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#27]
Let's say I have a list of exercises, e.g. objects of class SingleChoice. How do I make a section out of them? Is this the correct workflow?

```
sc_list <- list(new("SingleChoice", choices = letters[1:4]), new("SingleChoice", choices = letters[5:8]))
section <- new("AssessmentSection", assessment_item = sc_list)
test <- new("Assessmenttest", section)
create_qti_test(test)
```

I cannot run create_qti_test because it does not seem to be exported. But is it otherwise ok?

**Comment by shevandrin** [comment]
list in  assessment_item slot in AsessmentSection consists of AssessmentItemRef objects (links for xml files), I am on the path to make it possible to work with AssessmentItem objects

**Comment by shevandrin** [comment]
slot assessment_item works with all types of AssessmentItem 
see example in help for ?AssessmentTestOpal class
3483f61bf6278bea3802e8fc3dcd118afd5610ef
