### ISSUE TITLE
shuffling inside section?

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#29]
I believe in ONYX it is possible to select one exercise from a section randomly. Can we do this in qti? I just checked the section documentation and the test documentation, but did not find anything in it regarding this.

What I want to do is: I have about 50 scale level (single choice) questions; I make several sections and draw randomly one question from these sections.

**Comment by shevandrin** [comment]
I added some documentation
this is an example of your case:
```
sc1 <- new("SingleChoice", prompt = "Test task", title = "SC",
             identifier = "q1", choices = c("a", "b", "c"))
sc2 <- new("SingleChoice", prompt = "Test task", title = "SC",
             identifier = "q2", choices = c("A", "B", "C"))
sc3 <- new("SingleChoice", prompt = "Test task", title = "SC",
             identifier = "q3", choices = c("aa", "bb", "cc"))
exam_section <- new("AssessmentSection", identifier = "sec_id",
                   title = "section", assessment_item = list(sc1, sc2, sc3),
                   shuffle = TRUE, selection = 2)
exam <- new("AssessmentTestOpal", identifier = "id_test",
            title = "some title", section = list(exam_section))
create_qti_test(exam, "to delete")
```

**Comment by johannes-titz** [comment]
Works very well, thank you! I just noticed that one can create AssessmentTestOpal without a title. This makes it impossible to click the test in OPAL. Should we provide default titles for everything? Or force the user to put one?
