### ISSUE TITLE
Error in if (object@show_test_time) { : argument is of length zero

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#33]
Since a couple of days I am not able to use the package properly. It throws some errors. I tried to make a minimal example:

```
test <- AssessmentTestOpal(
  section = list(
    AssessmentSection(
      assessment_item = list(
        SingleChoice(choices = letters[1:4])
      )
    )
  )
)

create_qti_test(test, dir = "output")
```

results in:

Error in if (object@show_test_time) { : argument is of length zero

If I did something wrong in the minimal example, it should give a more useful error message. This error message is quite cryptic. I do not even know which object it refers to. If I add the slot, another slot throws the error.

I tried uninstalling and reinstalling without any changes. Not sure what it could be. Looks peculiar and it worked last week.

Since the package builds and checks are fine on github, I assume we are missing tests for AssessmentSection and or AssessmentTest?

If it works for you, I have to figure out what is different on my system. Package builds fine, I also ran checks locally, no problems.

**Comment by shevandrin** [comment]
we havent tests for AssessmentTest yet
i will look at this

**Comment by johannes-titz** [comment]
Ok, but you can work on what you are working on right now; it is not urgent. Do not let me distract you ;)

**Comment by shevandrin** [comment]
yea i am working on feedback system now, it is rather sophisticated on the first glance
If @bondarenko-petr cover AssessentTest functionality with tests,  it contributes to solve this kind of problems.
The ground of this kind of errors is missing initial values. With test it is faster to catch them ;)

**Comment by bondarenko-petr** [comment]
I have found the issue of function create_assessment_test() with different classes. This function has to be implemented another way @shevandrin. For example, if the argument of this function is AssessmentTest Class then it requests a file. But, it is a slot in another class - AssessmenrtTestOpal. 

Output in the console of R :
Error in create_assessment_test(object = exam) : 
  no slot of name "files" for this object of class "AssessmentTest"

**Comment by johannes-titz** [comment]
I just looked into this again. The example in the help file of AssessmentTestOpal actually works, even with create_qti_test (which by the way could be added to the example). So I was trying to figure out the difference between this example and my own. Interestingly, if I use new("AssessmentTestOpal", ...) it creates the xml files and then fails with 

`Error in if (!is.na(object@time_limits)) { : argument is of length zero`

Not sure why there is a difference between `new("AssessmentTestOpal` and just calling `AssessmentTestOpal`. Anyway, the errors persists, but is more informative now.

**Comment by johannes-titz** [comment]
Regarding the wrappers, please checkout this resource: https://adv-r.hadley.nz/s4.html

Currently, the code for the wrappers is not correct. Setting a type in r functions does not do anything, but prevents useful error messaging. Parameters that have defaults should be set to these defaults. I think this is the source of the problem.

**Comment by johannes-titz** [comment]
This was just a problem with the constructor helpers. Either we just use the "new" syntax or we have to write better helpers. 

Better helpers: take care of prototypes and parameters automatically.

**Comment by shevandrin** [comment]
@johannes-titz should we return to the constractor functions with do.call() as an alternative way to "new" to create objects ?

**Comment by johannes-titz** [comment]
We still have to put all values twice and if something changes we need to change it at two locations. It is much shorter though with do.call.
