### ISSUE TITLE
improvements for extract function

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#35]
I have some suggestions for the extract function:

- [x] ## improve colnames

file_name -> file
datestamp -> date
question_id -> id_question (to be consistent with id_answer_options)
in general plurals to singular, e.g. base_types -> base_type; I guess also for the function itself, "items", "exercises", singular should be sufficient
id_answer_options -> id_answer (maybe to unspecific?)
correct_response -> response_correct
cand_response -> response_candidate

For the exercises-level

candidate_score -> score_candidate
max_scores -> score_max

- [x] ## improve types

date should be converted to date type, e.g. via lubridate (see the cheatsheets)

response variables (correct and candidate) that are logicals (TRUE/FALSE) could be converted directly to numbers (1/0), then the processing is easier. Unfortunately these variables still have to be characters because of possible string-inputs for non-numeric exercises. 

- [x] ## hide user names

Can we have an option to make sha-sums from the file-names to have some data protection; I guess it should be even on by default. Now that I think about it, maybe the sha-sum is too long. Random names would also be possible, I guess, or just some number as an ID. Not sure if there are any disadvantages, but right now I cannot think of any.

- [x] ## documentation

Normally the description is short and the details are in the details section.

- [x] ## message

remove "what we have", the other infos are informative and should be kept

- [x] ## tolerance

Could we also extract tolerance values for the item level? The problem is that the tolerance values differ between exercises and there is no simple way to "grade" all exercises at once. Or maybe simpler: can we get the grading from opal on the item level? Whether an item is correct or not?

- [x] ## rid of duplicates

![image](https://github.com/shevandrin/qti/assets/43883261/6cf4770c-73da-4f34-9185-3fc8d91af51d)

- [x] add result extraction for directedPair base type
- [x] add result extraction for ordered cardinality

**Comment by shevandrin** [comment]
![image](https://github.com/shevandrin/qti/assets/43883261/6cf4770c-73da-4f34-9185-3fc8d91af51d)

- [ ] add result extraction for directedPair base type
- [ ] add result extraction for ordered cardinality

**Comment by shevandrin** [comment]
improved colnames:
on exercises level:
- file_name -> file
- datestamp -> date
- question_id -> id_question
- candidate_score -> score_candidate
- max_scores -> score_max
- titles -> title

on items level:
- file_name -> file
- datestamp -> date
- question_id -> id_question
- titles -> title
-  base_types -> base_type
- id_answer_options -> id_answer
