### ISSUE TITLE
mask password for API

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#36]
Password for API should be masked, e.g. via pass package. Since it only has to be entered once per session, I guess it is ok to ask the user for it. We can still save the username as system variable. I guess it should go into the Rprofile, not in .env, which I actually did not even know until now.

How about an ONYX API label? 

It is not urgent, though. I guess we should finish up with the interface first.

**Comment by shevandrin** [comment]
R profile to store username permanently
