### ISSUE TITLE
rendering of qti files in R/RStudio

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#4]
It would be nice if we could get a preview of a qti file in R/Rstudio. This should be possible with a minimal http-server and this js-library: https://github.com/QTIJS/QTI.JS

For the http-server we can just use the servr package.

@yulieth9109 can you test this setup with an example, please. If there are no problems, can you implement a function that does this automatically and checks for obvious problems (e.g. checking for already running server, stopping the server when certain things happen, etc.). The blogdown package does something very similar when calling serve_site (I believe this is the correct function, there are several related ones).

It would be great if we could use this function directly from RStudio with the Knit-Button (RMD to qti -> render). I believe this should be possible, some information on this is here: https://bookdown.org/yihui/rmarkdown-cookbook/custom-knit.html

By the way, this does not conflict with the REST API for OPAL, as many users will not use OPAL but need a way to render the exercise they are working on.

The render function should be in the qti package, the knit function rather in exam. We could move it to exam later though.

**Comment by yulieth9109** [comment]
@johannes-titz
I begin to read the documentation about the engine and It mentioned that it works for QTI V2.2. I would like to ask you if it is ok I work with that one or if I have to look for an engine that supports QTI v 2.1

**Comment by johannes-titz** [comment]
Good question, I tested it with the exams package and it worked very well, so I think there is no big difference between 2.1 and 2.2.
