### ISSUE TITLE
dir parameter can also be a file-path

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#40]
Sometimes it is necessary to write an xml file with a specific file name. Is it possible to accept a file path in this case? E.g. 

`rmd2qti("file.Rmd", dir = "othername.xml")`

Maybe it should be called path in this case?

**Comment by johannes-titz** [comment]
Is this a misunderstanding? For QTIJS it is useful to return an xml, which seems to be faster for rendering. But for opal we need a zip anway. Maybe we can make both? Maybe `rmd2test`? Or `rmd2zip`? Or is `rmd2qti` to unspecific? `rmd2xml` or `rmd2task` instead?

This specific issue was more about the file naming. For QTIJS a single file must be named index.xml. If dir is available, usually a path also works, but not in this case. So I needed to rename the produced file.

**Comment by shevandrin** [comment]
@johannes-titz ok, got your idea
i suggest:
- rmd2task -> returns xml for task
- rmd2zip -> returns zip, that contains one task from Rmd content

we  can switch to other names later

**Comment by johannes-titz** [comment]
In thise case I think I prefer rmd2xml and rmd2zip, it is a file ending in both cases.

**Comment by shevandrin** [comment]
so far we have to functions:
1. rmd2zip -> creates an xml file from rmd document and wraps it into test, returns a zip archive with tests, param 'path' allows to put file name as well, the target folder will be cleaned initially (exception for cleaning the working directory, i think it is reasonable to protect it, @johannes-titz what do you think?)
2. rmd2xml -> creates an xml file from rmd document and return it, param 'path' allows to put file name as well

**Comment by johannes-titz** [comment]
Looks good to me. I will try it out on a real scenario. I guess we can close this for now?
