### ISSUE TITLE
additional non-object parameters in yaml section

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#41]
I need to use the parameter `knit` in the yaml section, which is not a qti-object parameter. When calling rmd2qti, the object creater tries to make sense of this additional parameter, which it cannot. I guess we need to ignore some parameters in object creation, of which one should be `knit`. Maybe this is the only one, maybe not.

Let me know if this is specific enough or I should add more information.

I can try to fix it myself first.

**Comment by johannes-titz** [comment]
Is this ok with you, @shevandrin  (in create_question_object)

```r
attrs <- yaml.load(parsermd::as_document(attrs_sec))
# ignore parameters that are not related to object creation
attrs <- attrs[! names(attrs) %in% c("knit")]`
```

**Comment by shevandrin** [comment]
that is completely ok!
