### ISSUE TITLE
create_qti_test option to delete previous content

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#42]
Working on a series of exercises I repeatedely create the corresponding test with `create_qti_test` and then render it. Sometimes the identifiers change, which leaves me with leftovers from previous generations. I guess in most cases the previous files can/should be deleted?

**Comment by shevandrin** [comment]
Initially my idea is: create_qti_test() should only return one zip archive (like in exams package). I left other files for a while. Should I rid of them now?

**Comment by johannes-titz** [comment]
Actually I like that both (zipped, unzipped) are created. It is useful to see what is in the zip. Maybe we can just delete the content of the folder from the previous run? I was also wondering: the zip is created from scratch, right? Because in the system zip command it usually updated an existing archive.

**Comment by shevandrin** [comment]
It takes the content of folder with files and wrap them into archive. Is it called 'scratch'?  Sorry for dummy questions 😞

**Comment by johannes-titz** [comment]
From scratch means from beginning, or from 0.

Okay, I think then it would be better to clean the folder first or what do you think? Otherwise there can be leftover files from previous runs.
