### ISSUE TITLE
Running tests with multiple cores

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#43]
Is there any problem if we switch to multiple cores for testing? https://cran.r-project.org/web/packages/testthat/vignettes/parallel.html

I just tried it and it takes <1min on my pc, before that about 2.5min. Since our tests are very static and independent I do not see any apparent issues. Just wanted to ask before pushing.

**Comment by shevandrin** [comment]
all our tests are independent, we can try

**Comment by johannes-titz** [comment]
Seems to be fine, right? Can we close this?
