### ISSUE TITLE
InlineChoice inconsistent naming

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#44]
InlineChoice has slot "options", whereas other classes have options "choices" (e.g. SingleChoice). Is there a specific reason for that (qti naming)?

**Comment by shevandrin** [comment]
no specific reason, but InlineChoice is inherited from Gap-class (it is independent from AssessmentItem). I can switch to "choices", it makes the tesaurus of workflow less, that is better

**Comment by shevandrin** [comment]
names are changed:
'options'->'choices'
'options_identifiers'->'choices_identifiers'
