### ISSUE TITLE
finishing up mpc exercises

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#45]
I started to write the tutorial on mpc, we can gather information on what is still needed:

- [x] allow shortcut `type: mpc` in yaml
- [x] default points if points is not given, maybe 0.5*number of choices
- [ ] #58

**Comment by shevandrin** [comment]
about the third problem:
unfortunately * *Not* valid* was parced like new list inside the parent list, and then gives some chank in italics
- * *Not* valid*
gives <li> <ul> <li> <em>
it leads to error in reading html as well.
As a solution we can assign other way to denote right answers in list (specific tag or set of symbols)
z.B:
- !!! *Not* valid

**Comment by johannes-titz** [comment]
Okay, maybe we can ignore it for now. A user who wants it could also use html tags directly. I will put in the documentation on sc and mpc.
