### ISSUE TITLE
name of outcomeIdentifier for modalFeedback

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#48]
I explored the details of qtijs regarding showing feedback. I found the following problem and resolution:

In one generated xml file from Rmd I have:

``<modalFeedback identifier="modal_feedback" outcomeIdentifier="FEEDBACK" showHide="show">
    <p>The used qti version is 2.1.</p>
  </modalFeedback>
``

When qtijs tries parsing this file it gets the outcomeIdentifier FEEDBACK but when trying to show the feedback it does not find this identifier in the object because it does not exist. I do not fully understand what the outcomeIdentifier is supposed to do, but simply changing it to FEEDBACKMODAL is sufficient. Ist this just a qtijs quirk or do we have to use specific names for these identifiers? In the outcomeDeclarations FEEDBACK is not declared, whereas FEEDBACKMODAL is. If this is indeed a strict requirement, why did we miss it so far? Do we have to change something in the tests? If there is a different explanation, nevermind :).

**Comment by shevandrin** [comment]
As my memory serves me right, there is no restrictions for the name of identifiers. Besides that they must started with letter. So, I need to switch them to 'F..MODAL', right? It takes a little time

**Comment by johannes-titz** [comment]
We can discuss it on Friday. I do not fully understand what is happening. I thought the outcomeIdentifier must be declared beforehand.
