### ISSUE TITLE
essay xml files are missing declaration of RESPONSE

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#50]
I generated the following file via rmd2zip (response processing is excluded for brevity):

```
<?xml version="1.0" encoding="UTF-8"?>
<assessmentItem xmlns="http://www.imsglobal.org/xsd/imsqti_v2p1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.imsglobal.org/xsd/imsqti_v2p1 http://www.imsglobal.org/xsd/qti/qtiv2p1/imsqti_v2p1.xsd" identifier="essay1" title="essay1" adaptive="false" timeDependent="false">
  <outcomeDeclaration identifier="SCORE" cardinality="single" baseType="float">
    <defaultValue>
      <value>0</value>
    </defaultValue>
  </outcomeDeclaration>
  <outcomeDeclaration identifier="MAXSCORE" cardinality="single" baseType="float">
    <defaultValue>
      <value>1</value>
    </defaultValue>
  </outcomeDeclaration>
  <outcomeDeclaration identifier="MINSCORE" cardinality="single" baseType="float">
    <defaultValue>
      <value>0</value>
    </defaultValue>
  </outcomeDeclaration>
  <outcomeDeclaration identifier="FEEDBACKBASIC" cardinality="single" baseType="identifier">
    <defaultValue>
      <value>empty</value>
    </defaultValue>
  </outcomeDeclaration>
  <outcomeDeclaration identifier="FEEDBACKMODAL" cardinality="multiple" baseType="identifier">
    <defaultValue>
      <value/>
    </defaultValue>
  </outcomeDeclaration>
  <itemBody>
    <p>What are the advantages and disadvantages of the <code>qti</code> package as compared to the <code>exams</code> package?</p>
    <extendedTextInteraction responseIdentifier="RESPONSE"/>
  </itemBody>
...
...
  <modalFeedback identifier="modal_feedback" outcomeIdentifier="FEEDBACK" showHide="show">
    <p>The qti package can only export to the QTI format, which makes it less general than the <code>exams</code> pacakge. But the qti package supports more exercise types, can preview xml files and has a very solid core architecture based on S4 OOP and many tests.</p>
  </modalFeedback>
</assessmentItem>
```

Check out the responseIdentifier in the extendedTextInteraction, which is "RESPONSE". It is not defined beforehand. In the examples from QTI it is defined. For instance: https://www.imsglobal.org/question/qtiv2p1/examples/items/extended_text.xml

This produces similar problems as before to qtijs. It tries to find variables that do not exist. I am wondering how we can avoid these problems in general because it seems the generated files are still consistent with the schema. Maybe we have to check it manually?

I would suggest that we include more tests of the official QTI examples. If we had a test for the extended_text.xml, we would have noticed this before.

**Comment by shevandrin** [comment]
now render_xml() with Essay works good!

according the qti information model responseProcessing can be missed:
Contains : [responseDeclaration](https://www.imsglobal.org/question/qtiv2p1/imsqti_infov2p1.html#element10073) [*]
`* `- usually it means 0, 1 or more.
when in schema 0 is needed to exclude, it is used:
[mapEntry](https://www.imsglobal.org/question/qtiv2p1/imsqti_infov2p1.html#element10070) `[1..*]`
