### ISSUE TITLE
improve helpers for gaps

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#52]
`gap_numeric` should have better defaults:

- score = 1
- expected_length to our strange formula of +7?
- type_precision = "exact"

value_precision can be called precision, but right now I think maybe we should call it tolerance because you describe it as tolerance in the text. tolerance and tolerance_type?

response can be called solution? or correct_response?

"thy answer" typo in the description for response_identifer

Why is value string; map yaml? What does map yaml mean?

- [x] change slot-names and params of helpers:
response -> solution
value_precision -> tolerance
type_precision -> tolerance_type

- [x] rid of alternatives slot and param from TextGap and gap_text; for the alternatives use solution as a vector of values
- [x] change order of params and slots:
gap_numeric(): solution, tolerance, tolerance_type, score, response_identifier, include_lower|upper_bound, expected_length, plasceholder
gap_text(): solution, tolerance, case_sensitive, score, response_identifier, expected_length, placeholder

- [x] assign default values for params in helpers:
score = 1
expected_lenght = ?
tolerance_type = ? absolute (if tolerance), exact (if is.null(tolerance)

**Comment by shevandrin** [comment]
all names in params of gep_text() are the same as names of slots related classes.  
map yaml  means that it is an **one line yaml format**, by default yaml record is  a set of line.
all default values are controlled by class description, but we can add them here as well

**Comment by shevandrin** [comment]
- [ ] change slot-names and params of helpers:
response -> solution
value_precision -> tolerance
type_precision -> tolerance_type

- [ ] at least in helper for text-gap merge solution and alternatives
- [ ] change order of params and slots:
gap_numeric(): solution, tolerance, tolerance_type, score, response_identifier, include_lower|upper_bound, expected_length, plasceholder
gap_text(): solution, tolerance, case_sensitive, score, response_identifier, expected_length, placeholder

- [ ] assign default values for params in helpers:
score = 1
expected_lenght = ?
tolerance+type = ?

**Comment by shevandrin** [comment]
should we provide 'expected_length' with value? it handles by class initiation,  if user miss the value here, then class initiation calculates the value

**Comment by johannes-titz** [comment]
I think we should provide it with a default value.

**Comment by bondarenko-petr** [comment]
The size of the gap was defined according to Firefox Browser
![image](https://github.com/shevandrin/qti/assets/117097478/756dc5bd-5689-4f70-a6b2-232a92a4392a)

**Comment by bondarenko-petr** [comment]
1. Google Chrome
![2023-08-25_14-35-47](https://github.com/shevandrin/qti/assets/117097478/2cdfca76-9f23-4d63-826b-7e21d2933ca0)
2. Firefox
![2023-08-25_14-34-34](https://github.com/shevandrin/qti/assets/117097478/8a067b7d-67d0-48e8-a90f-7b504b9a77e7)
