### ISSUE TITLE
some problems with dropdowns in OPAL

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#54]
I am experimenting with the low level functions and created several dropdown questions without providing points. The result looks like this:

https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/40512782337?8

When I answer everything correctly it shows that I have 4 out of 1 points, which does not make much sense. The code is a bit complicated and I do not have a minimal reprex, but I can show you the code next time.

Then I tried to upload our template for dropdowns, which looks like this: https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/40513077248?0

Unfortunately, this fails completely when I answer it, giving in OPAL:

> An error occurred while executing this test. In most cases this is caused by unexpected test contents.

The points are also displayed as 1.

You can access the source file via RStudio: New RMarkdown, from Template, dropdown (simple).

Interestingly, when I load the exercise to ONYX, the points are corrected to 2 and the exercise itself works just fine. Can we check what OPAL is doing to this file and maybe do this beforehand? It feels we are not providing all information that is necessary. This is not about a perfect copy of the OPAL file, rather about providing enough information for OPAL to work properly.

By the way, the feedback also does not show up.

I guess we also need to think of tests for these cases.

**Comment by johannes-titz** [comment]
I just realized that even incorrect answers are treated as correct. In the first link above just send the answers without clicking anything will give 4 points. The produced xml has as default values for all SCORE variables 1. I think we need to revise the xml building process. Specifically the defaults for QTI variables. MAXSCORE seems also to be set to 1 by default , even though there are individual exercises with 4 points in sum.

I assume that when importing into ONYX, ONYX fixes these issues automatically, but it would be better if we take into account these things beforehand. Otherwise, our xml files might not work in other LMS.

Maybe this also explains the broken exercises, when directly uploading an xml to OPAL.

**Comment by shevandrin** [comment]
i did some improvements, it was common problem for gaps and dropdowns
Now points for the whole task (Entry-type) is recalculated as a sum of scores of individual gaps and dropdowns
It should help ;)

**Comment by johannes-titz** [comment]
Nice, I will check it out, probably tomorrow. Then we can close this.

**Comment by johannes-titz** [comment]
Points now show correctly on OPAL, but exercise submission still throws an error: https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/40569143297

**Comment by shevandrin** [comment]
i did some improvements, in my case now it works https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/40571568129?10
you should try again ;)

**Comment by shevandrin** [comment]
unfortunately, my example also doesn't  work properly, so I continue to find an issue...

**Comment by shevandrin** [comment]
i did some improvements, in my example it works now https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/40585560074

the problem was in order of processing outcome variables, we have to stick the same order as opal has

now i need to check the order for all types of tasks
