### ISSUE TITLE
order exercise, default scoring

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#55]
I just made an order exercise via Rmd. The description of the class says that `points_pwer_answer` defaults to true, but check out the behavior of the exercise: 

https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/40597192706

I get 0 points if I have 2 correct, which should get me 0.5 points. (2 points overall, 8 questions).

**Comment by shevandrin** [comment]
@bondarenko-petr could you make specific tests for this mechanic?
