### ISSUE TITLE
wrappers for gap_numeric fail (conceptual problem?)

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#56]
For a specific exercise, I would like to set some defaults for gap_numeric, but this fails:

```
gap_helper <- function(solution) {
    gap_numeric(round(solution, 2), tolerance = 1, tolerance_type = "relative")
}
gap_helper(3)
```

Error message: Error in FUN(X[[i]], ...) : object 'solution' not found

Do you have an idea why? Is it solvable?

**Comment by shevandrin** [comment]
$solution
round(solution, 2)

$tolerance
[1] 1

$tolerance_type
[1] "relative"

this what gap_numeric gets, as you see the value of solution is other expression
i dont know how to fix it yet

**Comment by shevandrin** [comment]
i found the solution, i will fix it in 30 min

**Comment by shevandrin** [comment]
for gap_numeric() it is ok now
i am doing the same for other helpers
