### ISSUE TITLE
math in Rmd remove spaces

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#62]
I remember that we talked about extra spaces for math, but it actually looks not the way I thought it would:

https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/40609546250?11

Can we remove the extra spaces before the commas? For instance, N=156_, -> N=156,

**Comment by shevandrin** [comment]
![image](https://github.com/shevandrin/qti/assets/43883261/5253aa87-d330-4385-a6d0-0f9056034871)
after refactoring of `create_questin_object()` it looks fine
