### ISSUE TITLE
automatic calculation of points for test

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#66]
It would be useful to get the number of overall points from a test object. For instance, one creates am exam and wants to know if the number of points is enough or one needs to add more exercises. Currently the points are set to 0, even though it could be calculated from the sections/exercises in the constructor.

**Comment by shevandrin** [comment]
@johannes-titz i did some implementations, now when new class AssessmentTest is creating, the points are calculating, could you check this functionality?

**Comment by johannes-titz** [comment]
Seems to work fine, so I will close this.
