### ISSUE TITLE
generates id for rows and cols in MatchTable

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/qti#69]
using abbreviate() generate identifiers for rows and cols in MatchTable types

**Comment by shevandrin** [comment]
@johannes-titz just specify abbr_id: true in yaml section in Rmd to generate abreviations as identifiers
example:
`---
title: test example
type: table
abbr_id: true
knit: qti::render_rmd
---`
@johannes-titz can you give me feedback

**Comment by johannes-titz** [comment]
Error in .nextMethod(.Object = .Object, ... = ...) : 
  invalid name for slot of class “OneInRowTable”: abbr_id

You should exclude abbr_id in object creation? Although I guess it could also be implemented directly on the class level. Rows and columns by numbers is not informative.

**Comment by shevandrin** [comment]
> Error in .nextMethod(.Object = .Object, ... = ...) : invalid name for slot of class “OneInRowTable”: abbr_id
> 
> You should exclude abbr_id in object creation? Although I guess it could also be implemented directly on the class level. Rows and columns by numbers is not informative.

we can not do this on class level, because right answers are pairs of identifiers (row_id+col_id), and if user doesnt control assigning of identifiers of cols and rows, how can he assign  the pairs, that define right answers

**Comment by johannes-titz** [comment]
Okay, nevermind!

**Comment by shevandrin** [comment]
> 

for us probably it is better to make attr_id=true as defaul, because we are interested in extracting resuls

**Comment by bondarenko-petr** [comment]
We need to fix the problem of generating an abbreviation for DirectedPair Class. If we have one word, we should leave one word as an abbreviation for the identifier -- @shevandrin

**Comment by shevandrin** [comment]
@bondarenko-petr check how it works

**Comment by bondarenko-petr** [comment]
All is good! We can close this issue. @shevandrin
