### ISSUE TITLE
xslt processing to create usable format for analysis from qti actual exams files

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#7]
be careful to provide an anonymous file

needs to be improved, but this is the general way:
1. read in xml exam file [I still need to provide one!]
2. apply xslt
3. do some wrangling
4. output df

```
getrow <- function(file) {
  doc <- read_xml(file)
  style <- read_xml("test.xml")
  html <- xml_xslt(doc, style)
  writeLines(as.character(html), con = "test.csv")
  d <- read.csv("test.csv")

  d$correctResponse <- as.numeric(d$correctResponse)

  # at the moment we are only interested in section 28
  df <- d %>%
    filter(grepl("section_28", identifier)) %>%
    mutate(candidateResponse = ifelse(is.na(candidateResponse), F, candidateResponse),
           solved = candidateResponse == correctResponse,
           id = substr(file, 8, 14))
  df
}
```

test.xml (can probably be improved a lot):
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:d1="http://www.imsglobal.org/xsd/imsqti_v2p1">
<xsl:output method="text"/>
<xsl:template match="/d1:assessmentResult">correctResponse, identifier,candidateResponse
<xsl:for-each select="//d1:itemResult">
<xsl:for-each select="d1:responseVariable/d1:correctResponse">
  <xsl:value-of select="d1:value"/>,<xsl:value-of select="../@identifier"/>,<xsl:value-of select="../d1:candidateResponse/d1:value"/><xsl:text>&#10;</xsl:text>
    </xsl:for-each>
    </xsl:for-each>
</xsl:template>
</xsl:stylesheet>
```

**Comment by shevandrin** [comment]
here it is a function that can extract all values for duration from given xml-file

get_duration <- function(file) {
    doc <- xml2::read_xml(file)
    test_duration <- xml2::xml_find_all(doc, ".//d1:testResult/d1:responseVariable")
    ids_test <- xml2::xml_attr(test_result, attr = "identifier")
    val_test <- xml2::xml_text(test_result)
    items_result <- xml_find_all(doc, ".//d1:itemResult")
    ids_item <- xml2::xml_attr(items_result, attr = "identifier")
    val_node <- xml2::xml_find_all(doc, ".//d1:itemResult/d1:responseVariable[@identifier='duration']")
    val_item <- xml2::xml_text(val_node)
    data <- data.frame(identifier = c(ids_test, ids_item),
                       values = as.numeric(c(val_test, val_item)))
    return(data)
}

**Comment by shevandrin** [comment]
which information do you want to extract from the result files?

**Comment by johannes-titz** [comment]
Can you add it to the repo and post an example here, please.

Regarding the results file as much info as is possible. The question (or at least the first couple of words), question id, score, solution of participant, actual solution. Probably more, but I have to think about it.

**Comment by shevandrin** [comment]
it gives more attributes (id, duration, candidate score, max score).

```
get_result_attributes <- function(file) {
    doc <- xml2::read_xml(file)
    items_result <- xml_find_all(doc, ".//d1:itemResult")
    ids_item <- xml2::xml_attr(items_result, attr = "identifier")
    dur_nodes <- xml2::xml_find_all(doc, ".//d1:itemResult/d1:responseVariable[@identifier='duration']")
    durations <- xml2::xml_text(dur_nodes)
    score_nodes <- xml2::xml_find_all(doc, ".//d1:itemResult/d1:outcomeVariable[@identifier='SCORE']")
    scores <- xml2::xml_text(score_nodes)
    maxscore_nodes <- xml2::xml_find_all(doc, ".//d1:itemResult/d1:outcomeVariable[@identifier='MAXSCORE']")
    maxes <- xml2::xml_text(maxscore_nodes)
    data <- data.frame(identifier = ids_item,
                       duration = as.numeric(durations),
                       score = as.numeric(scores),
                       max_scores = as.numeric(maxes))
    return(data)
}
```

**Comment by shevandrin** [comment]
In this function the problem with missed candidate answers solved. The function was exported.
