### ISSUE TITLE
error in render opal

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/qti#77]
knitting works in non-interactive mode, it means that we can not use menu() to ask user which file should be replaced or should qti create new resource on opal.
Possible solution: always add new resource on opal during call render_opal in Rmd file. To make less mess we can add prefix 'knit' to display_name for such resources (like 'knit_test').
@johannes-titz what do you think?

**Comment by johannes-titz** [comment]
I like the prefix knit; but I would overwrite the previous files. Otherwise there will be too many files when developing and testing an exercise. Maybe a message can be displayed.
