### ISSUE TITLE
S4 implementation

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#8]
This could be a milestone consisting of several tasks, we will need to discuss this, but maybe after having working solutions for all exercise types.

**Comment by johannes-titz** [comment]
Up to date guide on S4 with exercises: https://adv-r.hadley.nz/s4.html

**Comment by shevandrin** [comment]
according to this guide:
naming for class names - UpperCamelCase
for methods - lowerCamelCase

should we do it the same way?
if yes, how should we entitled other functions? now it is xxx_xxxxx_xxxxx

**Comment by johannes-titz** [comment]
I will close this since we have the S4 implementation.
