### ISSUE TITLE
meaningful identifiers for rows in MatchTable

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/qti#80]
So far there are three ways to provide values for rows identifiers:
1.  default values: row1, row2, ... rowN
2.  abbreviation if in yaml there is `abbr_id: true`
3.  from csv file. In this case we can have two columns for this: 
- -one for meaningful identifiers that should be read as `row.names` 
- -the second one is for question sentence or expression
example of csv:
```
"", "","alfa","beta", "gamma"
"id_row_1", "question expression 1", 0, 0, 1
"id_row_2", "question expression 2", 0, 1, 0
"id_row_3", "question expression 3", 0, 1, 0
```
in rmd make import via `read_csv(... row.names = 1, ...)`

@johannes-titz please correct the description if I am mistaken

**Comment by johannes-titz** [comment]
abbr_id -> abbreviate_id, here we can afford a longer name I think

I do not understand the second description of point 3. I would say we can just use the row.names if they are present, reading in data has to be done by the user, so he has to be sure that row names are properly read in.

**Comment by shevandrin** [comment]
@bondarenko-petr could you cover test this new way of abbreviation

**Comment by bondarenko-petr** [comment]
@shevandrin I covered the tests in this new way of abbreviation.

**Comment by shevandrin** [comment]
so far for user-defined identifiers in csv or markdown table it is needed to add special columns with predefined titles: `rowid` and/or `colid`

so the table with user-defined identifiers can look like:

|X     |rowid |alfa |beta |gamma |
|:-----|:-----|:----|:----|:-----|
|row1  |id1   |0    |0    |1     |
|row2  |id2   |0    |1    |0     |
|row3  |id3   |0    |1    |0     |
|colid |      |alf  |bet  |gmm   |

@bondarenko-petr there is a need to cover it with tests
