### ISSUE TITLE
upload2opal conveniences

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#82]
Can we have convenience functions for these cases:

- [x] quickly uploading an rmd file to opal; should call the render function, zip the file and upload it
- [x] quickly uploading an xml file to opal; should zip the file and upload it (as far as I remember, uploading xml without test did not work)

**Comment by shevandrin** [comment]
@johannes-titz should the zip archives been stored in both cases? or it is better to rid of them as leftovers?

**Comment by shevandrin** [comment]
new convenience functions:
- rmd2opal(file)
- xml2opal(file)
