### ISSUE TITLE
template single choice complex, asterisks ignored?

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#85]
This template uses asterisks that seem to be ignored:

https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/41868820510?1

Option 1.2 is treated as the correct one.

Is it because of the comment following the option?

**Comment by johannes-titz** [comment]
Oh, right. Makes sense. Then identifier should overwrite filename for display_name, right?

**Comment by shevandrin** [comment]
> Oh, right. Makes sense. Then identifier should overwrite filename for display_name, right?
> 
> Alternatively, we can make copies of templates in inst/exercises and name them accordingly.

yes, identifier is used as file name,  and in its turn file name is used as a display_name, if it is not given
I see that you stick some pattern for identifiers TOPICN_QM, we can use it for all templates to avoid duplicates

**Comment by johannes-titz** [comment]
Allright; for vignette images it does not matter anyway.
