### ISSUE TITLE
vignette dropdown

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#89]
## dropdown helper

parameter `solution` is problematic because actually it is the choices. 

`solution` -> `choices`
`answer_index` -> `solution`

answer_index can be numeric, then it is the index; or it can be the actual string, which is often better because it is more explicit. We need to check if the solution is actually there, but I guess the constructor will complain if not.

choices_identifiers, here I do not think we need two parameters for choices and identifiers. I would like to specify it this way: `choices = c("c1" = "S4 OOP", "c2" = "S3 OOP", ...))`

`score` -> `points`

The helper function seems to work even when I specify parameters that do not exist.

```
choices <- c("c1" = "S4 OOP", "c2" = "S3 OOP", "c3" = "no OOP", "c4" = "R6 OOP")
oop_task <- dropdown(choices = choices, solution = "S4 OOP",
                     response_identifier = "OOP_task")
oop_task
```

gives: 
```
#> [1] "<gap>{solution: [S4 OOP], answer_index: 1.0, points: 1.0, shuffle: yes, response_identifier: OOP_task, choices_identifiers: [S4 OOP,S3 OOP,no OOP,R6 OOP], type: InlineChoice}</gap>"
```

## other

One general question: why do we need to specify the type for gaps and dropdowns; the type can be inferred from the content directly.

___________________

list of changes:

- [x] In dropdown(): solution -> choices; answer_index we keep or answer_index ->  solution; jt: I prefer solution_index
- [x] in dropdown():  choices can be given as a list with identifiers choices = c("c1" = "S4 OOP", "c2" = "S3 OOP", ...))
- [x] in dropdown(): rid of `choices_identifiers `

Optional for now (low prio):
- [x]  for gap and dropdown there is not need to specify type in yaml section of Rmd

**Comment by shevandrin** [comment]
> answer_index can be numeric, then it is the index; or it can be the actual string, which is often better because it is more explicit. We need to check if the solution is actually there, but I guess the constructor will complain if not.

what if the choices are also numeric, how we can differentiate when answer_index is the index and when it is a right answer?

**Comment by shevandrin** [comment]
> The alternative is to use two parameters, solution_index, solution_string; only one should be provided.

I vote for this approach with two parameters

> The helper function seems to work even when I specify parameters that do not exist.

this function just creates a string during knitting (that is why it works), and after that it creates class according to data from this string.  String from your example will through an error for InlineChoice class


> One general question: why do we need to specify the type for gaps and dropdowns;

i am not sure what you mean here. In helpers we do not specify the class via parameters in function, we use different functions for different types of gaps/drowdown. Since we dont have common set of parameters for each type, i created 3 funcitons for 3 types of gaps/dropdown.

**Comment by johannes-titz** [comment]
Ok, then let's go for the approach you vote for. Throw an error if both are specified.

Ok, but still wondering why the function is continuing despite parameters that are not there; is `...` used? I guess in general ok if it still throws an error. But for vignettes it does not, so the result is unexpected.

Regarding the last one: Just saying that if I do not specify type: gap or type: dropdown; I still can infer the type, because the user uses `r dropdown` or `r gap`. Unless of course he uses <<...>>, which I assume is unspecific, could be a dropdown or a gap? I kind of still would like type inference to save time, since I only use `r gap` and `r dropdown`, but not of high priority right now.

**Comment by johannes-titz** [comment]
I have second thoughts. Maybe index is enough. I forgot that the default is 1. So best practices is just to put the correct choice as the first element in choices. I guess this is rather intuitive and clear. Or do you object? If not, we can just use solution_index. Or is QTI using answer_index? I find answer_index a bit unspecific.

**Comment by shevandrin** [comment]
> Ok, but still wondering why the function is continuing despite parameters that are not there; is `...` used? I guess in general ok if it still throws an error. But for vignettes it does not, so the result is unexpected.

i am not sure that i can explain it in this message) all helpers take all parameters from the environment of function, i dont need params with NULL values, they throght an error later, when i put them into new("") construction. We can discuss it offline.

**Comment by johannes-titz** [comment]
Alright, makes sense. Should be fine for general use. I just have to keep an eye out in the vignette.

**Comment by shevandrin** [comment]
> Regarding the last one: Just saying that if I do not specify type: gap or type: dropdown; I still can infer the type, because the user uses `r dropdown` or `r gap`. Unless of course he uses <<...>>, which I assume is unspecific, could be a dropdown or a gap? I kind of still would like type inference to save time, since I only use `r gap` and `r dropdown`, but not of high priority right now.

in this example <<type: TextGap, ...>> the creator has to put the type of gap. With helpers the creator use specific function for specific type of gap - so helpers (gap_text, gap_numeric, dropdown) do not have a type as a parameter of function

**Comment by shevandrin** [comment]
> have second thoughts. Maybe index is enough. I forgot that the default is 1. So best practices is just to put the correct choice as the first element in choices. I guess this is rather intuitive and clear. Or do you object? If not, we can just use solution_index. Or is QTI using answer_index? I find answer_index a bit unspecific.

less parameters is better ) so solution_string we dont need anymore

**Comment by johannes-titz** [comment]
Sure thing; I'll be more explicit:

```
---
knit: qti::render_opal
---

The gap defines the `r gap_text("type")` and I do not need to put anything inside the yaml section.
```

Similarly for gap_numeric, combined with gap_text. And for dropdowns. Low priority though.

**Comment by shevandrin** [comment]
> Sure thing; I'll be more explicit:

so in yaml section of Rmd we dont need to provide type as attribute, we need to define the appropriate type according to the content.  Now i got this

For me it becomes more clear, if there is no type in yaml section, then process with Rmd as 'gap' type of task

**Comment by johannes-titz** [comment]
Well, not necessarily gap; depends on content. But let's leave this for now. Maybe we can do it in the second release.

**Comment by shevandrin** [comment]
> Well, not necessarily gap; depends on content. But let's leave this for now. Maybe we can do it in the second release.

is your idea that we dont need type in yaml section in all exercises?

**Comment by johannes-titz** [comment]
Well that would be my dream :), but we discussed beforehand that it is too fragile. Still, I believe for certain types, it should be easy to implement, e.g. gaps, dropdowns for starters.

**Comment by shevandrin** [comment]
list of changes:

- [ ] In dropdown(): solution -> choices; answer_index we keep or answer_index ->  solution
- [ ] in dropdown():  choices can be given as a list with identifiers choices = c("c1" = "S4 OOP", "c2" = "S3 OOP", ...))
- [ ] in dropdown(): rid of `choices_identifiers `
- [ ]  for gap and dropdown there is not need to specify type in yaml section of Rmd
