### ISSUE TITLE
vignette qti

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#91]
- [x] add image for quick start

workflow image ( I really like this!):
- [x] add knit functions
- [x] create zip Test, maybe there is a better description for that? It is not always zipped. "write QTI file"?
- [x] "upload to learning management system", Opal is too specific, right?
- [x] user experience, this sound like the users are testing the exercise and giving feedback; maybe there is a better description
- [x] get raw data of outcomes; hmm, raw data is not clear; maybe "read tests results in QTI format"

**Comment by shevandrin** [comment]
> * add knit functions

i somehow mentioned knit functions on the first step -> visualize outcomes -> use knit...
could you give me more details what you would like to see with knit functions?


> * create zip Test, maybe there is a better description for that? It is not always zipped. "write QTI file"?

Imsglobal uses work 'package', how do you find this: "write and package QTI files"?


> * "upload to learning management system", Opal is too specific, right?

to make it shorter i would suggest: "upload to LMS"

> * user experience, this sound like the users are testing the exercise and giving feedback; maybe there is a better description

my suggestion is "passing the test by students"


> * get raw data of outcomes; hmm, raw data is not clear; maybe "read tests results in QTI format"

i agree that "raw data" is too specific) but i dont like the verb "read" either, bcs it doesnt imply any outcome of action.
my suggestion here is "extract data from the QTI  report about the results"

**Comment by johannes-titz** [comment]
> > * add knit functions
> 
> i somehow mentioned knit functions on the first step -> visualize outcomes -> use knit... could you give me more details what you would like to see with knit functions?

Just mention the specific knit functions so the user knows what is available

> 
> > * create zip Test, maybe there is a better description for that? It is not always zipped. "write QTI file"?
> 
> Imsglobal uses work 'package', how do you find this: "write and package QTI files"?

sure

> 
> > * "upload to learning management system", Opal is too specific, right?
> 
> to make it shorter i would suggest: "upload to LMS"

ok

> 
> > * user experience, this sound like the users are testing the exercise and giving feedback; maybe there is a better description
> 
> my suggestion is "passing the test by students"

how about "run assessment"? Or maybe ims qti also has a word for that? 

> 
> > * get raw data of outcomes; hmm, raw data is not clear; maybe "read tests results in QTI format"
> 
> i agree that "raw data" is too specific) but i dont like the verb "read" either, bcs it doesnt imply any outcome of action. my suggestion here is "extract data from the QTI report about the results"

Why does "read" not imply an outcome of action?

**Comment by shevandrin** [comment]
> Or maybe ims qti also has a word for that?

i havent found something usefull, they usually stick "candidate responses"


> Why does "read" not imply an outcome of action?

it is just from my perspective, i am not insist) "read" is kind of not a proactive action in terms of working with data, but as general it is still fit

**Comment by johannes-titz** [comment]
"Collect candidate responses"?

"extract QTI results" to be consistent with the function name?

**Comment by shevandrin** [comment]
now after some thinking i prone to think that "read tests results from QTI report" can be more clear for final users

**Comment by johannes-titz** [comment]
is report the official word? it sounds to me like some sort of analysis.

**Comment by shevandrin** [comment]
https://www.imsglobal.org/question/qtiv2p1/imsqti_resultv2p1.html
here they are using 'report' as a noun in description of items
