### ISSUE TITLE
knitting of exercise fails when there is a chunk that is supposed to be displayed

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#93]
---
    type: gap
    knit: qti::render_qtijs
    ---
        
    # question

    ```{r echo=T}
    library(qti)
    iq <- round(rnorm(sample(7:13, 1), 100, sd = 15))
    ```
    
    You have a small sample of IQ values:
    
    `r iq`
    
    The mean is `r gap_numeric(round(mean(iq), 2))`.

Because echo=T, the whole thing fails:

pandoc: Heap exhausted;
pandoc: Current maximum heap size is 31457280 bytes (30 MB).
pandoc: Use `+RTS -M<size>' to increase it.
Error: pandoc document conversion failed with error 251
Execution halted

Usually one wants to hide the r commands, but not always. One could present some R code, the output and then ask a question.

**Comment by shevandrin** [comment]
> One could present some R code

present for user/student?

**Comment by johannes-titz** [comment]
Yep.

**Comment by shevandrin** [comment]
i thought that all things that should be displayed for user must be placed in question section. this is the only place, that i considered as a source of content to show.

**Comment by johannes-titz** [comment]
Of course! Sorry for the misunderstanding. Then the problem is: It will not knit at all, when I do not put echo=F.

**Comment by johannes-titz** [comment]
```
    ---
    type: gap
    knit: qti::render_qtijs
    ---
    
    ```{r echo=F}
    library(qti)
    iq <- round(rnorm(sample(7:13, 1), 100, sd = 15))
    ```
    
    # question
    
    ```{r echo=T}
    library(qti)
    iq <- round(rnorm(sample(7:13, 1), 100, sd = 15))
    ```
    
    You have a small sample of IQ values:
    
    `r iq`
    
    The mean is `r gap_numeric(round(mean(iq), 2))`.
    ```

This also does not work with the same error.

**Comment by shevandrin** [comment]
this how it is rendered on opal:
https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/42022961153?2
does it look as it should be?

**Comment by johannes-titz** [comment]
Looks ok to me. Then it is a problem of qtijs?

**Comment by shevandrin** [comment]
> Then it is a problem of qtijs?

i think so

**Comment by shevandrin** [comment]
> Although, on the second look, it is underlined, seems to be a link?

yea, strange behavior)

**Comment by johannes-titz** [comment]
So without any knit function, it knits to html with these parameters:


/usr/bin/pandoc +RTS -K512m -RTS gap1.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output gap1.html --lua-filter /home/jt/R/x86_64-pc-linux-gnu-library/4.3/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/jt/R/x86_64-pc-linux-gnu-library/4.3/rmarkdown/rmarkdown/lua/latex-div.lua --embed-resources --standalone --variable bs3=TRUE --section-divs --template /home/jt/R/x86_64-pc-linux-gnu-library/4.3/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable theme=bootstrap --mathjax --variable 'mathjax-url=https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --include-in-header /tmp/RtmpVbZR8n/rmarkdown-strebe4325c477d0.html 

which looks fine.

**Comment by johannes-titz** [comment]
Sorry, I have to bump this. One of our students needs the ability to output code chunks. The main problem is that there are no linebreaks for code. Can we find a quickfix? To reproduce you can use the example at the top, just move the code chunk to after #question.

Produces (missing the code line break after library(qti):


 library(qti) iq <- round(rnorm(sample(7:13, 1), 100, sd = 15)) 
You have a small sample of IQ values:

101, 88, 73, 94, 98, 99, 100, 94, 78, 104

The mean is 
 
 .

**Comment by shevandrin** [comment]
> Can we find a quickfix?

ok, i switch to this task
but when i find the right pandoc parameter, i need to rewrite object_builder.R, because i am expecting to get slightly differen structure of htm, so some adaptation is needed

**Comment by shevandrin** [comment]
i solve this, not it looks like this one [https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/42691690497?28](https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/42691690497?28))

**Comment by johannes-titz** [comment]
Very nice. Looks safe to me. Can we close it?
