### ISSUE TITLE
vignette section

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#94]
in section():

- [x] file -> files
- [x] num_variants -> n_variants?
- [x] the vignette should be in a separate category for pkgdown

Can `section` take other sections? I assumed that it does. Or do we have to use the oop-infrastructure for that?

Could upload2opal handle sections directly? In the vignette I create different sections and always have to wrap them into a test. The shortcut is to just do this automatically and give a message or warning. rather a convenience thing, low priority.

We still need to agree on the nested parameter. What if we just call it by_variants = TRUE/FALSE, by_files = TRUE/FALSE, without nested?

**Comment by shevandrin** [comment]
> We still need to agree on the nested parameter. What if we just call it by_variants = TRUE/FALSE, by_files = TRUE/FALSE, without nested?

both of them? or one of by_variants or by_files?

**Comment by shevandrin** [comment]
> Can `section` take other sections? I assumed that it does. Or do we have to use the oop-infrastructure for that?

function `section()` works only with file so far. I suppose objects should also be added.  If you agree i open the issue

**Comment by shevandrin** [comment]
> Could upload2opal handle sections directly? In the vignette I create different sections and always have to wrap them into a test. The shortcut is to just do this automatically and give a message or warning. rather a convenience thing, low priority.

`upload2opal()` works with files as well.  At least it will be good to allow to work with classes AssessmentTest and AssessmentTestOpal.  I am not sure about AssessmentSection, bcs in this case creator misses customization of test. we can discuss

**Comment by johannes-titz** [comment]
> > We still need to agree on the nested parameter. What if we just call it by_variants = TRUE/FALSE, by_files = TRUE/FALSE, without nested?
> 
> both of them? or one of by_variants or by_files?

not sure. Let's discuss on Tuesday.

Sections -> then the first parameter cannot be files, right? But it would be useful to combine sections into other sections. For instance, i create a random section and a permanent section, no I need to put them inside the root section, for which I need to use AssessmentSection.

upload2opal, yes test and testopal would be nice; I even think that AssessmentSection has its uses, but a warning or message should  be displayed.

**Comment by shevandrin** [comment]
> * the vignette should be in a separate category for pkgdown

could you clarify a little, what should i do here? create a new category in 'Articles' on web site, or?
