### ISSUE TITLE
improve templates rmarkdown

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#97]
- [ ] add filename as option
- [ ] add knitting engine as dropdown

I am wondering: do we need the prefix QTI in the template name. In the beginning I thought it is better because I assumed that the templates are ordered alphabetically. Now I realize they are ordered by the package name. Should we remove the prefix?

**Comment by shevandrin** [comment]
can you send me some links on packages with such templates. I didn't find any information how to do this 😢

**Comment by johannes-titz** [comment]
You are right, I couldn't find anything myself. There seems to be only one more parameter `create_dir`. In this case, we can leave it as it is. But there are templates where a file name can be provided, maybe this depends on create_dir...

**Comment by shevandrin** [comment]
![image](https://github.com/shevandrin/qti/assets/43883261/d4a31103-19f2-4308-a9e4-44d18bf45f97)
it appears when create_dir=T

**Comment by johannes-titz** [comment]
ok, not really useful for us i guess.
