### ISSUE TITLE
vignette tables

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/qti#98]
Is it possible to put negative points in the table?

- [x] rows_shuffle, cols_shuffle -> shuffle_rows, shuffle_cols

**Comment by shevandrin** [comment]
> Is it possible to put negative points in the table?

for individual questions it is possible, like multiple choice. The overall points for the whole task is always positive

**Comment by shevandrin** [comment]
@bondarenko-petr  change OOP class diagram according to new slot names
