### ISSUE TITLE
upload2opal() with objects AssessmentTest and AssessmentTestOpal

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/qti#99]
upload2opal, yes test and testopal would be nice; I even think that AssessmentSection has its uses, but a warning or message should  be displayed.

_Originally posted by @johannes-titz in https://github.com/shevandrin/qti/issues/94#issuecomment-1790661709_

upload2opal(file, ...) if we can put not only files, should we change the name of parameter file->??

upload2opal() in test should take:

- [x] Zip archive with test
- [x] Rmd
- [x] md
- [x] one xml with AssessmentItem
- [x] AssessmentTest
- [x] AssessmentTestOpal
- [x] AssessmentItem

**Comment by johannes-titz** [comment]
Well that's kind of the problem, it could be a file, a test, a section...but what is uploaded in any case is a test, right? Feels strange, but maybe test is the best right now?

**Comment by shevandrin** [comment]
https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/42698965017?7
